services:
  - type: web
    name: cartola-caos-java
    runtime: docker
    plan: free
    region: oregon # or your preferred region
    buildCommand: docker build -t cartola-caos-java .
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: cartola-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: cartola-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cartola-db
          property: password
      - key: CARTOLA_TOKEN
        value: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg5NWIwYmIwLTI4ODMtNDE3MC1hMDY2LTZkMDIwZjkzNGRlMyIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiY2FydG9sYS13ZWJAYXBwcy5nbG9ib2lkIl0sImF6cCI6ImNhcnRvbGEtd2ViQGFwcHMuZ2xvYm9pZCIsImVtYWlsIjoicm9kcmlnb2pvcm5vb2tpQGdtYWlsLmNvbSIsImV4cCI6MTc1ODM5NzM2NiwiZmVkZXJhdGVkX3NpZCI6IjFiOGQ0MTk2YzgwMTlhZDE4MzRkNzYwMmY4ZTA1ZjMyZjc0NmU2YTQ0NDQ3MzU2NDM0YjRlNzY1YTU5NTY0NjQyNjM1NDUyNGQ0NzM1NTA1NTQzMzc2MjMzNTY1NTYxNzY0ODc4NTQ2MzQ1MzY1NjU2NTk2NzcxNTU3MDU4NGI0OTQxMzM2NzUyNGQ2MTU0NGI2MzU4NGY1MjczMzE2OTZlNzkyZDQ2Njc2ZTM5NGMyZDc0NjQ0ODQ5Njc0OTRhNGU0YjM1NDM1ZjU5NzczZDNkM2EzMDNhNmE2ZjcyNmU2ZjZmNmI2OTVmNzI2ZjY0NzI2OTY3NmYiLCJmc19pZCI6InRuakREc1ZDS052WllWRkJjVFJNRzVQVUM3YjNWVWF2SHhUY0U2VlZZZ3FVcFhLSUEzZ1JNYVRLY1hPUnMxaW55LUZnbjlMLXRkSElnSUpOSzVDX1l3PT0iLCJnbGJpZCI6IjFiOGQ0MTk2YzgwMTlhZDE4MzRkNzYwMmY4ZTA1ZjMyZjc0NmU2YTQ0NDQ3MzU2NDM0YjRlNzY1YTU5NTY0NjQyNjM1NDUyNGQ0NzM1NTA1NTQzMzc2MjMzNTY1NTYxNzY0ODc4NTQ2MzQ1MzY1NjU2NTk2NzcxNTU3MDU4NGI0OTQxMzM2NzUyNGQ2MTU0NGI2MzU4NGY1MjczMzE2OTZlNzkyZDQ2Njc2ZTM5NGMyZDc0NjQ0ODQ5Njc0OTRhNGU0YjM1NDM1ZjU5NzczZDNkM2EzMDNhNmE2ZjcyNmU2ZjZmNmI2OTVmNzI2ZjY0NzI2OTY3NmYiLCJnbG9ib19pZCI6ImQ4OTFlNTM4LTAzN2UtNDNhZS04M2QzLWM1ZWVhMzEzY2E1NCIsImlhdCI6MTc1ODM5Mzc2NSwiaXNzIjoiaHR0cHM6Ly9nb2lkYy5nbG9iby5jb20vYXV0aC9yZWFsbXMvZ2xvYm8uY29tIiwianRpIjoiOWFlMWE5NzMtNDhkYi00NzU4LThkYjItODdhZmIyYjQ3MTBjIiwibm9uY2UiOiI1Yzk0MTQyNC00NDJjLTQ1NWYtOGNmNC04MDIxYTk4OTI5ZTEiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqb3Jub29raV9yb2RyaWdvIiwic2NwIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJnbGJpZCIsImJpcnRoZGF0ZSJdLCJzZXNzaW9uX3N0YXRlIjoiZjJiMDkxYjUtNGI5My00YjJlLWFlZWYtOWIxYzg3YWY1Y2E3Iiwic2lkIjoiZjJiMDkxYjUtNGI5My00YjJlLWFlZWYtOWIxYzg3YWY1Y2E3Iiwic3ViIjoiZDg5MWU1MzgtMDM3ZS00M2FlLTgzZDMtYzVlZWEzMTNjYTU0IiwidHlwIjoiQmVhcmVyIn0.o8CtwPAL3JQCr_0b_D7J8WCc5Z9LbUkZOSmoTZzthagiOUfLW4YAA9FKCwZFjKzvR4ok5RBOfVz0x4X6t5yN8jgXukG6XXvQFJ_klMHW6yqN_qPdLCNa_Suor84nZeEa_YnphcrWc_7QDK0V1A6fTnaQCvSfVyFnZxMa6rgaoYq9pSXBWN3aeCotXMJD3yghyyWKKa29m54J1uMd-LjeQuetOylyQEpJqFBJIEHvy6D_9-21hGcr9k7MA_IqINS2J2KPOg6PQaebcUYrjIxqBO9TfLWHfC0GeU9Jak6yFPikDF62QPI4iBc6al2Ir2rSOY1Aczpo-FxQQKsBgknAKg
      - key: ALLOWED_ORIGINS
        value: "*"
    healthCheckPath: /actuator/health
    
  - type: pserv
    name: cartola-db
    runtime: postgresql
    plan: free
    region: oregon # or your preferred region
    databaseName: cartola_db
    user: cartola_user